apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv
  namespace: flask-app
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/pv0001/"
